### ISSUE TITLE
Selection color is generic gray in Nemo

### ISSUE THREAD

**Issue by ThatOneCalculator** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#1]
When selecting an item in a list (in Nemo, GTK3), the color is gray. Perhaps replace it with `#403d52` (highlight med) or `#524f67` (highlight high)?

![image](https://user-images.githubusercontent.com/44733677/174933607-e80cb941-76e8-46ce-b9d0-5ab95ed7a1e5.png)

**Comment by Fausto-Korpsvart** [comment]
The theme is now updated with support for Gnome 46.
