### ISSUE TITLE
Pop OS 

### ISSUE THREAD

**Issue by Marlon-Sbardelatti** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#10]
I quite new to this so idk if im doing something wrong. But there is some way to make the menu aplications and the search menu in pop os match this theme? 
 
![Screenshot from 2023-10-12 14-12-04](https://github.com/Fausto-Korpsvart/Rose-Pine-GTK-Theme/assets/117592329/72d7f932-e1e2-41f1-abb1-7ba90c4ca74f)
![Screenshot from 2023-10-12 14-13-12](https://github.com/Fausto-Korpsvart/Rose-Pine-GTK-Theme/assets/117592329/65403e9d-5d56-475e-964a-628a4d0a318e)

**Comment by spxctreofficial** [comment]
Not entirely sure what Pop OS uses in the desktop environment. If it uses Gnome (pretty certain it does, that looks like Gnome) you need to install the `gnome-tweaks` package from your package manager and then set your theme there.

**Comment by Fausto-Korpsvart** [comment]
The theme is now updated with support for Gnome 46.
