### ISSUE TITLE
Possibility of integration into Rose-pine's official repo

### ISSUE THREAD

**Issue by maybork** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#2]
Hi!
I'd like to ask you if it'd be fine by you for me to add a variation of your GNOME Shell theme into [Rose Pine's repo](https://github.com/rose-pine/gtk/). I know the license allows for such distribution but I want to make sure that would be okay.
Thanks,
Ash

**Comment by Fausto-Korpsvart** [comment]
> Hi! I'd like to ask you if it'd be fine by you for me to add a variation of your GNOME Shell theme into [Rose Pine's repo](https://github.com/rose-pine/gtk/). I know the license allows for such distribution but I want to make sure that would be okay. Thanks, Ash

Sure, of course you can, I'm happy to help. };-]

**Comment by maybork** [comment]
Thank you! I mentioned you as a contributor :smile:

**Comment by Fausto-Korpsvart** [comment]
> Thank you! I mentioned you as a contributor smile

Thank you, I hope to make the missing themes soon.
