### ISSUE TITLE
What CSS code to make the close, minimize and maximize buttons smaller?

### ISSUE THREAD

**Issue by pierre-rs** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#5]
Hi,

Please, would you know what would be the CSS code to be able to reduce the size of the close/minimize/maximize buttons in the title bar of GTK3 application windows?

I'm using RosePine-Main-BL theme on Gnome 43.

I believe that whatever CSS code manages to reduce the size of the title bar buttons should be changed or added in the ~/.themes/RosePine-Main-BL/gtk-3.0/gtk-dark.css file, right?

**Comment by Fausto-Korpsvart** [comment]
The theme is now updated with support for Gnome 46.
