### ISSUE TITLE
Suggestion to tone down white buttons and selection a bit

### ISSUE THREAD

**Issue by maboleth** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#6]
I like this theme a lot! Thank you.

But I have a slight problem with the white buttons like here. Notice the home button or arrow in the "script" - it's barely visible.

![Untitled](https://user-images.githubusercontent.com/2467520/216955535-3b1c2478-c6de-415d-8139-67c6cb64b229.png)

Also it is the same color in file selection.
![Untitled2](https://user-images.githubusercontent.com/2467520/216956255-6ac15761-0525-45cd-90f2-d42a4dfb25d2.png)

I think it should be toned down to something dimmer or less bright, maybe more 'rosey' color why not. White can be too 'strict' and cold.

**Comment by Fausto-Korpsvart** [comment]
> I like this theme a lot! Thank you.
> 
> But I have a slight problem with the white buttons like here. Notice the home button or arrow in the "script" - it's barely visible.
> 
> ![Untitled](https://user-images.githubusercontent.com/2467520/216955535-3b1c2478-c6de-415d-8139-67c6cb64b229.png)
> 
> Also it is the same color in file selection. ![Untitled2](https://user-images.githubusercontent.com/2467520/216956255-6ac15761-0525-45cd-90f2-d42a4dfb25d2.png)
> 
> I think it should be toned down to something dimmer or less bright, maybe more 'rosey' color why not. White can be too 'strict' and cold.

Thanks for reporting, I'm checking the issues to update soon, I'll put this on my to-do list.

Thanks for your support.
