### ISSUE TITLE
Some libadwaita/gtk4 apps have a border around the tabs within the app

### ISSUE THREAD

**Issue by n3thshan** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#7]
[Screencast from 2023-03-27 08-05-47.webm](https://user-images.githubusercontent.com/97467958/227827153-510b6ca4-e867-46b5-9184-3b7d1c7e21c2.webm)

**Comment by Fausto-Korpsvart** [comment]
> 

Thanks for the report, as soon as I have time I will check and make an update.

Thanks for the support.

**Comment by Fausto-Korpsvart** [comment]
The theme is now updated with support for Gnome 46.
