### ISSUE TITLE
Currently broke on gnome 44

### ISSUE THREAD

**Issue by NeuronSooup** [Fausto-Korpsvart/Rose-Pine-GTK-Theme#8]
After a long time of no updates, this theme had some minor inconsistencies and bugs until now it is broken

https://imgur.com/a/4D9fgrj

**Comment by Fausto-Korpsvart** [comment]
> After a long time of no updates, this theme had some minor inconsistencies and bugs until now it is broken
> 
> https://imgur.com/a/4D9fgrj

I know, I have recently started to update the themes to support Gnome 44, `Tokyonight and Gruvbox` are already updated, in the following days I will continue with the other themes.

Thanks for reporting }:-]

**Comment by NeuronSooup** [comment]
Good to know and thank you

**Comment by Fausto-Korpsvart** [comment]
The theme is now updated with support for Gnome 46.
